# Basis Sets

All basis sets used for Compuatational Chemistry must satisify the following two integrals over all space: <br>

$$\int{\psi^*_i\psi_{i} d\tau} = 1$$
$$\int{\psi^*_{i}\psi_j d\tau}=0$$

In [7]:
import math
import numpy as np
import scipy.integrate as integrate

#Set Up Plotly for graphing
from plotly.offline import iplot, init_notebook_mode
init_notebook_mode(connected=True)

## Harmonic Oscillator 

All information presented here originates from <b>The Simple Harmonic Oscillator</b> written by Daniel V. Schroeder. <br>
<br>
The normalized Harmonic Oscillator function is:
$$\psi_n(r)=\frac{1}{\sqrt{2^nn!\sqrt{\pi}}}H_n(r)e^{\frac{-r^2}{2}}$$ <br>
<br>
$H_n$ signifies the nth Hermite polynomial. All information in this document regarding the Hermite Polynomials originates from <b>Hermite Polynomials in Quantum Harmonic Oscillator</b> by Christos T. Aravanis. <br>
<br>
The Hermite polynomials are calculated by $H_n(r)=(-1)^ne^{r^2}\frac{d^n}{dr^n}e^{-r^2}$ for $n\in\mathbb N$, and from a computational standpoint, the following expression equivalent to the above is used:
$$H_n(r) = \sum_{k=0}^{[n/2]}{\frac{(-1)^kn!}{k!(n-2k)!}(2x)^{n-2k}}$$ <br>
$[n/2]$ signifies the largest integer less than or equal to $x$.

In [15]:

#returns the normalization constant for the Harmonic Oscillator Function
def C(n):
    return 1 / math.sqrt( (pow(2, n) * math.factorial(n) * math.sqrt(math.pi)) )


#Returns a lambda function of the nth hermite polynomial
def hermite(n, k):
    
    c = pow(-1, k) * math.factorial(n) / ( math.factorial(k) * math.factorial(n - 2*k) )
        
    if(k == 0):
        return lambda r : c * pow(2*r, n-(2*k))
    else:
        return lambda r : c * pow(2*r, n-(2*k)) + hermite(n, k-1)(r)

def buildHermite(n):
    
    return hermite(n, n // 2)

#Creates a new Harmonic Oscillator function
#and returns it as a lambda function
def newHO(n):
    return lambda r : C(n) * buildHermite(n)(r) * math.exp(-pow(r,2)/2)

basis = []
size = 20
S = np.zeros([size, size])

for i in range(size):
    basis.append( newHO(i) )
    
for i in range(size):
    for j in range(size):
        S[i,j] += integrate.quad(lambda x : basis[i](x) * basis[j](x), -20, 20)[0]
        if(abs(S[i, j]) < pow(10, -10) ):
            S[i, j] = 0
        
print(S)

#prepare data for use with graphing
figure = { 
    "data": [
        
        #create the Hartree-Fock generated Potential Energy Surface
        {
            "type":"scatter",
            "x":list(range(0, 20)),
            "y":[x for x in range(0, 10)],
            "mode":"markers", 
            "name":"Ps1",
            "marker":{"color":"blue"}
        },
        
    ]
}

iplot(figure)

    

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.